/* 
 * NEM SPs
 *
 * TestNet SP API Endpoint
 *
 * OpenAPI spec version: v0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using io.spfs.NeutoSpfs.Api;
using io.spfs.NeutoSpfs.Model;
using io.spfs.NeutoSpfs.Client;
using System.Reflection;

namespace io.spfs.NeutoSpfs.Test
{
    /// <summary>
    ///  Class for testing BinaryTransactionEncryptedMessage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BinaryTransactionEncryptedMessageTests
    {
        // TODO uncomment below to declare an instance variable for BinaryTransactionEncryptedMessage
        //private BinaryTransactionEncryptedMessage instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BinaryTransactionEncryptedMessage
            //instance = new BinaryTransactionEncryptedMessage();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BinaryTransactionEncryptedMessage
        /// </summary>
        [Test]
        public void BinaryTransactionEncryptedMessageInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BinaryTransactionEncryptedMessage
            //Assert.IsInstanceOfType<BinaryTransactionEncryptedMessage> (instance, "variable 'instance' is a BinaryTransactionEncryptedMessage");
        }

        /// <summary>
        /// Test the property 'Hash'
        /// </summary>
        [Test]
        public void HashTest()
        {
            // TODO unit test for the property 'Hash'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Size'
        /// </summary>
        [Test]
        public void SizeTest()
        {
            // TODO unit test for the property 'Size'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
