/* 
 * NEM SPs
 *
 * TestNet SP API Endpoint
 *
 * OpenAPI spec version: v0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using io.spfs.NeutoSpfs.Api;
using io.spfs.NeutoSpfs.Model;
using io.spfs.NeutoSpfs.Client;
using System.Reflection;

namespace io.spfs.NeutoSpfs.Test
{
    /// <summary>
    ///  Class for testing PrivateKey
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PrivateKeyTests
    {
        // TODO uncomment below to declare an instance variable for PrivateKey
        //private PrivateKey instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PrivateKey
            //instance = new PrivateKey();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PrivateKey
        /// </summary>
        [Test]
        public void PrivateKeyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PrivateKey
            //Assert.IsInstanceOfType<PrivateKey> (instance, "variable 'instance' is a PrivateKey");
        }

        /// <summary>
        /// Test the property 'Raw'
        /// </summary>
        [Test]
        public void RawTest()
        {
            // TODO unit test for the property 'Raw'
        }

    }

}
