/* 
 * NEM SPs
 *
 * TestNet SP API Endpoint
 *
 * OpenAPI spec version: v0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using io.spfs.NeutoSpfs.Client;
using io.spfs.NeutoSpfs.Api;
using io.spfs.NeutoSpfs.Model;

namespace io.spfs.NeutoSpfs.Test
{
    /// <summary>
    ///  Class for testing DownloadsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class DownloadsApiTests
    {
        private DownloadsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new DownloadsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DownloadsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' DownloadsApi
            //Assert.IsInstanceOfType(typeof(DownloadsApi), instance, "instance is a DownloadsApi");
        }

        
        /// <summary>
        /// Test DownloadFileUsingNemHashAndEncryptedHashUsingGET
        /// </summary>
        [Test]
        public void DownloadFileUsingNemHashAndEncryptedHashUsingGETTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string nemhash = null;
            //string xPubkey = null;
            //var response = instance.DownloadFileUsingNemHashAndEncryptedHashUsingGET(nemhash, xPubkey);
            //Assert.IsInstanceOf<ResponseEntity> (response, "response is ResponseEntity");
        }
        
        /// <summary>
        /// Test DownloadPlainMessageFileUsingNemHashUsingGET
        /// </summary>
        [Test]
        public void DownloadPlainMessageFileUsingNemHashUsingGETTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string nemhash = null;
            //var response = instance.DownloadPlainMessageFileUsingNemHashUsingGET(nemhash);
            //Assert.IsInstanceOf<ResponseEntity> (response, "response is ResponseEntity");
        }
        
        /// <summary>
        /// Test DownloadRawBytesSecureMessageFileUsingNemHashUsingGET
        /// </summary>
        [Test]
        public void DownloadRawBytesSecureMessageFileUsingNemHashUsingGETTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string nemhash = null;
            //string xPvkey = null;
            //var response = instance.DownloadRawBytesSecureMessageFileUsingNemHashUsingGET(nemhash, xPvkey);
            //Assert.IsInstanceOf<byte[]> (response, "response is byte[]");
        }
        
        /// <summary>
        /// Test DownloadSecureMessageFileUsingNemHashUsingGET
        /// </summary>
        [Test]
        public void DownloadSecureMessageFileUsingNemHashUsingGETTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string nemhash = null;
            //string xPvkey = null;
            //var response = instance.DownloadSecureMessageFileUsingNemHashUsingGET(nemhash, xPvkey);
            //Assert.IsInstanceOf<ResponseEntity> (response, "response is ResponseEntity");
        }
        
    }

}
