/* 
 * NEM SPs
 *
 * TestNet SP API Endpoint
 *
 * OpenAPI spec version: v0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using io.spfs.NeutoSpfs.Client;
using io.spfs.NeutoSpfs.Api;

namespace io.spfs.NeutoSpfs.Test
{
    /// <summary>
    ///  Class for testing NodesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class NodesApiTests
    {
        private NodesApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new NodesApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of NodesApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' NodesApi
            //Assert.IsInstanceOfType(typeof(NodesApi), instance, "instance is a NodesApi");
        }

        
        /// <summary>
        /// Test CheckNodeUsingGET
        /// </summary>
        [Test]
        public void CheckNodeUsingGETTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.CheckNodeUsingGET();
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        
        /// <summary>
        /// Test GetNodeInfoUsingGET
        /// </summary>
        [Test]
        public void GetNodeInfoUsingGETTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetNodeInfoUsingGET();
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        
    }

}
