/* 
 * NEM SPs
 *
 * TestNet SP API Endpoint
 *
 * OpenAPI spec version: v0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using io.spfs.NeutoSpfs.Client;
using io.spfs.NeutoSpfs.Api;
using io.spfs.NeutoSpfs.Model;

namespace io.spfs.NeutoSpfs.Test
{
    /// <summary>
    ///  Class for testing SearchApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class SearchApiTests
    {
        private SearchApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new SearchApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SearchApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' SearchApi
            //Assert.IsInstanceOfType(typeof(SearchApi), instance, "instance is a SearchApi");
        }

        
        /// <summary>
        /// Test GrabPlainMessageTransactionUsingGET
        /// </summary>
        [Test]
        public void GrabPlainMessageTransactionUsingGETTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string nemhash = null;
            //var response = instance.GrabPlainMessageTransactionUsingGET(nemhash);
            //Assert.IsInstanceOf<BinaryTransactionEncryptedMessage> (response, "response is BinaryTransactionEncryptedMessage");
        }
        
        /// <summary>
        /// Test GrabSsecureMessageTransactionUsingGET
        /// </summary>
        [Test]
        public void GrabSsecureMessageTransactionUsingGETTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string nemhash = null;
            //string xPvkey = null;
            //var response = instance.GrabSsecureMessageTransactionUsingGET(nemhash, xPvkey);
            //Assert.IsInstanceOf<BinaryTransactionEncryptedMessage> (response, "response is BinaryTransactionEncryptedMessage");
        }
        
        /// <summary>
        /// Test GrabTransactionUsingGET
        /// </summary>
        [Test]
        public void GrabTransactionUsingGETTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string nemhash = null;
            //string xPubkey = null;
            //var response = instance.GrabTransactionUsingGET(nemhash, xPubkey);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        
        /// <summary>
        /// Test SearchAssetWithKeyUsingGET
        /// </summary>
        [Test]
        public void SearchAssetWithKeyUsingGETTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string searchKey = null;
            //string xPubkey = null;
            //var response = instance.SearchAssetWithKeyUsingGET(searchKey, xPubkey);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        
        /// <summary>
        /// Test SearchAssetWithNemHashUsingGET
        /// </summary>
        [Test]
        public void SearchAssetWithNemHashUsingGETTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string nemhash = null;
            //string xPubkey = null;
            //var response = instance.SearchAssetWithNemHashUsingGET(nemhash, xPubkey);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        
    }

}
